### ISSUE TITLE
Textarea with validation error throwing warning

### ISSUE THREAD

**Issue by lpedretti** [maiconpinto/cakephp-adminlte-theme#25]
While text inputs and other inputs as well seem to work ok, when a textarea field has a validation error it is throwing me this warning

Warning (2): trim() expects parameter 1 to be string, array given [CORE/src/View/Helper.php, line 190]

I solved it by editing cakephp's native Helper::addClass() method as follows

public function addClass(array $options = [], $class = null, $key = 'class')
    {
                /* added this check to fix adminlte's textareas */
		if (is_array($options[$key])) {
			$options[$key][] = $class;
			return $options;
		}
        if (isset($options[$key]) && trim($options[$key])) {
            $options[$key] .= ' ' . $class;
        } else {
            $options[$key] = $class;
        }

        return $options;
    }

I don't know if it's a cakephp error or adminlte's formhelper's.

Best regards!

Warning (2): trim() expects parameter 1 to be string, array given [CORE/src/View/Helper.php, line 190]
Code Context
trim - [internal], line ??
Cake\View\Helper::addClass() - CORE/src/View/Helper.php, line 190
Cake\View\Helper\FormHelper::_initInputField() - CORE/src/View/Helper/FormHelper.php, line 2499
Cake\View\Helper\FormHelper::textarea() - CORE/src/View/Helper/FormHelper.php, line 1574
AdminLTE\View\Helper\FormHelper::textarea() - ROOT/vendor/maiconpinto/cakephp-adminlte-theme/src/View/Helper/FormHelper.php, line 94
Cake\View\Helper\FormHelper::_getInput() - CORE/src/View/Helper/FormHelper.php, line 1171
Cake\View\Helper\FormHelper::input() - CORE/src/View/Helper/FormHelper.php, line 1074
AdminLTE\View\Helper\FormHelper::input() - ROOT/vendor/maiconpinto/cakephp-adminlte-theme/src/View/Helper/FormHelper.php, line 82
include - APP/Template/Element/Contacts/form.ctp, line 80
App\View\AppView::_evaluate() - APP/View/AppView.php, line 67
Cake\View\View::_render() - CORE/src/View/View.php, line 975
Cake\View\View::_renderElement() - CORE/src/View/View.php, line 1365
Cake\View\View::element() - CORE/src/View/View.php, line 501
include - APP/Template/Quotes/edit.ctp, line 75
App\View\AppView::_evaluate() - APP/View/AppView.php, line 67
Cake\View\View::_render() - CORE/src/View/View.php, line 975
Cake\View\View::render() - CORE/src/View/View.php, line 599

**Comment by maiconpinto** [comment]
Hello @lpedretti , I fixed the issue #25 with a small change. I tested here and it work, but let me know about how I can help you.

**Comment by atalayk** [comment]
This issue still exist when it's used with $validatior->notBlank('fieldname')    rule.
Warning (2): trim() expects parameter 1 to be string, array given [CORE/src/View/Helper.php, line 200]

**Comment by maiconpinto** [comment]
@atalayk you can help me with this problem? I could not reproduce the error. 
I created a new application for example, and configured the "description" field with notBlank and notEmpty, but it's work fine. 

![screenshot from 2017-06-27 14-48-58](https://user-images.githubusercontent.com/1476940/27602051-d7ffec14-5b47-11e7-81eb-ec46a2877093.png)
